// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI1FSt_Jn63VEmRYEQNGuXTFGsuKQSNqo',
    appId: '1:219186194521:web:2dd8ae319cf32e6b9ae948',
    messagingSenderId: '219186194521',
    projectId: 'khip01-comment-section',
    authDomain: 'khip01-comment-section.firebaseapp.com',
    databaseURL: "https://khip01-comment-section-default-rtdb.firebaseio.com",
    storageBucket: 'khip01-comment-section.appspot.com',
    measurementId: 'G-WRWZKK32D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNS-CWI9n6epfdVehk5x2C9VfzRmZqxRM',
    appId: '1:219186194521:android:1ce6f26dbf25524a9ae948',
    messagingSenderId: '219186194521',
    projectId: 'khip01-comment-section',
    storageBucket: 'khip01-comment-section.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Q76dufzNhpHALO3bxZYjp8dYSADgTac',
    appId: '1:219186194521:ios:3085d41dfac7b6409ae948',
    messagingSenderId: '219186194521',
    projectId: 'khip01-comment-section',
    storageBucket: 'khip01-comment-section.appspot.com',
    iosBundleId: 'com.khip01.app.commentSection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Q76dufzNhpHALO3bxZYjp8dYSADgTac',
    appId: '1:219186194521:ios:ef9d738b881f70a09ae948',
    messagingSenderId: '219186194521',
    projectId: 'khip01-comment-section',
    storageBucket: 'khip01-comment-section.appspot.com',
    iosBundleId: 'com.khip01.app.commentSection.RunnerTests',
  );
}
